import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

import { Manrope, Roboto } from "next/font/google";
import { ReactLenis } from "@/lib/lenis";
import { cn } from "@/lib/utils";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 400 500 600 700 800 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const font = Manrope({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
    display: "swap",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    // `${geistSans.variable} ${geistMono.variable}`,
                    font,
                    "antialiased",
                    "mx-auto bg-neutral-950"
                )}
            >
                <ReactLenis root>{children}</ReactLenis>
            </body>
        </html>
    );
}
